### PR TITLE
Loader option for the script element attributes

### PR DESCRIPTION
**Pull request by jorenham**
With added default `async` and `defer` attributes (as is recommended in the [docs](https://developers.google.com/recaptcha/docs/invisible)).

And some bonus typo fixes :)

### CODE REVIEW

**Comment by WipeAir** [comment]
Hi, thanks for the PR!

Is there an actual need to use `defer` and `async`? As the loader creates the script element by itself, the "onload" callback is already available.

**Comment by jorenham** [comment]
When the script that loads in the recaptcha script itself isn't `async` / `defer`, this matters I believe.

**Comment by WipeAir** [comment]
I still don't understand what you're trying to solve. There is no way the loader isn't available when reCAPTCHA finished loading. As the loader itself creates the script element for reCAPTCHA and proceeds after the reCPATCHA script has been loaded.

Feel free to correct me if I'm wrong :)

**Comment by jorenham** [comment]
https://stackoverflow.com/a/41289721/1627479
So `async` isn't needed, but adding `defer` will ensure that the loaded script will only start loading once the page has finished parsing, avoiding a longer load time in case the script is added before that time, e.g.

```html
<html>
<head>
<script src='recaptcha-v3.js'></script>
<script>load('<site key>').then(recaptcha => ...)</script>
<script src="very-big-script.js">
</head>
...
```

So here rendering blocks when loading each js script, and the async recaptcha script will be loaded concurrently with `very-big-script.js`, which could increase the time it'll take to get to parsing the page (e.g. with a slow connection).

**Pull request closed without merging**
